//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MexPointClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/MexPointServer")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyMath")]
    public interface IMyMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Add", ReplyAction="http://tempuri.org/IMyMath/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyMath/Add", ReplyAction="http://tempuri.org/IMyMath/AddResponse")]
        System.IAsyncResult BeginAdd(int a, int b, System.AsyncCallback callback, object asyncState);
        
        int EndAdd(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Write", ReplyAction="http://tempuri.org/IMyMath/WriteResponse")]
        MexPointClient.ServiceReference1.Person Write(string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyMath/Write", ReplyAction="http://tempuri.org/IMyMath/WriteResponse")]
        System.IAsyncResult BeginWrite(string name, string surname, System.AsyncCallback callback, object asyncState);
        
        MexPointClient.ServiceReference1.Person EndWrite(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMathChannel : MexPointClient.ServiceReference1.IMyMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WriteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WriteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MexPointClient.ServiceReference1.Person Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MexPointClient.ServiceReference1.Person)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathClient : System.ServiceModel.ClientBase<MexPointClient.ServiceReference1.IMyMath>, MexPointClient.ServiceReference1.IMyMath {
        
        private BeginOperationDelegate onBeginAddDelegate;
        
        private EndOperationDelegate onEndAddDelegate;
        
        private System.Threading.SendOrPostCallback onAddCompletedDelegate;
        
        private BeginOperationDelegate onBeginWriteDelegate;
        
        private EndOperationDelegate onEndWriteDelegate;
        
        private System.Threading.SendOrPostCallback onWriteCompletedDelegate;
        
        public MyMathClient() {
        }
        
        public MyMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddCompletedEventArgs> AddCompleted;
        
        public event System.EventHandler<WriteCompletedEventArgs> WriteCompleted;
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAdd(int a, int b, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAdd(a, b, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAdd(System.IAsyncResult result) {
            return base.Channel.EndAdd(result);
        }
        
        private System.IAsyncResult OnBeginAdd(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int a = ((int)(inValues[0]));
            int b = ((int)(inValues[1]));
            return this.BeginAdd(a, b, callback, asyncState);
        }
        
        private object[] OnEndAdd(System.IAsyncResult result) {
            int retVal = this.EndAdd(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCompleted(object state) {
            if ((this.AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCompleted(this, new AddCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAsync(int a, int b) {
            this.AddAsync(a, b, null);
        }
        
        public void AddAsync(int a, int b, object userState) {
            if ((this.onBeginAddDelegate == null)) {
                this.onBeginAddDelegate = new BeginOperationDelegate(this.OnBeginAdd);
            }
            if ((this.onEndAddDelegate == null)) {
                this.onEndAddDelegate = new EndOperationDelegate(this.OnEndAdd);
            }
            if ((this.onAddCompletedDelegate == null)) {
                this.onAddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCompleted);
            }
            base.InvokeAsync(this.onBeginAddDelegate, new object[] {
                        a,
                        b}, this.onEndAddDelegate, this.onAddCompletedDelegate, userState);
        }
        
        public MexPointClient.ServiceReference1.Person Write(string name, string surname) {
            return base.Channel.Write(name, surname);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWrite(string name, string surname, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWrite(name, surname, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MexPointClient.ServiceReference1.Person EndWrite(System.IAsyncResult result) {
            return base.Channel.EndWrite(result);
        }
        
        private System.IAsyncResult OnBeginWrite(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            string surname = ((string)(inValues[1]));
            return this.BeginWrite(name, surname, callback, asyncState);
        }
        
        private object[] OnEndWrite(System.IAsyncResult result) {
            MexPointClient.ServiceReference1.Person retVal = this.EndWrite(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWriteCompleted(object state) {
            if ((this.WriteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WriteCompleted(this, new WriteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WriteAsync(string name, string surname) {
            this.WriteAsync(name, surname, null);
        }
        
        public void WriteAsync(string name, string surname, object userState) {
            if ((this.onBeginWriteDelegate == null)) {
                this.onBeginWriteDelegate = new BeginOperationDelegate(this.OnBeginWrite);
            }
            if ((this.onEndWriteDelegate == null)) {
                this.onEndWriteDelegate = new EndOperationDelegate(this.OnEndWrite);
            }
            if ((this.onWriteCompletedDelegate == null)) {
                this.onWriteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWriteCompleted);
            }
            base.InvokeAsync(this.onBeginWriteDelegate, new object[] {
                        name,
                        surname}, this.onEndWriteDelegate, this.onWriteCompletedDelegate, userState);
        }
    }
}
